.PHONY: clean
clean:
	stack clean --full

.PHONY: docs
docs:
	stack haddock --open

.PHONY: deps
deps:
	stack build --copy-compiler-tool hlint implicit-hie BNFC

.PHONY: format
format:
	find rulecheck -name '*.hs' | xargs -t stack exec -- stylish-haskell -i

.PHONY: lint
lint:
	stack exec -- hlint -i 'Parse error' -i 'Reduce duplication' -i 'Use <=<' rulecheck/src demo-domain/src

.PHONY: gen-hie
gen-hie:
	stack exec -- gen-hie > hie.yaml
