resolver: lts-19.27

ghc-options:
  "$everything": -haddock

extra-deps:
- little-logger-1.0.1
- little-rio-1.0.1
- int-like-0.1.1

packages:
- searchterm
- rulecheck
- demo-domain
- package-tests/algebraic-graphs-test

#   Uncomment below to enable fuzz testing for the demo app
# - demo-test

# Uncomment to fuzz "Color", for example
# To run the fuzz tests use the command `stack test Color-test`
# - package-tests/Color-test

# Uncomment to use the local version of "Color", for example
# This might be necessary if you want to make some changes to the module
# to facilitate testing (e.g. expose a hidden module containing rewrite rules)
# - ../haskell-packages/Color-0.3.3
#
# Other packages with similar changes necessary
- ../haskell-packages/aeson-2.0.3.0
- ../haskell-packages/algebraic-graphs-0.6.1
- ../haskell-packages/arithmoi-0.12.0.2

# Added via ./test.sh
- package-tests/arithmoi-test
- package-tests/fast-math-test
