name:                {testname}
version:             0.1.0

dependencies:
- base >= 4.12 && < 5

default-extensions:
- BangPatterns
- ConstraintKinds
- DeriveAnyClass
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- KindSignatures
- MultiParamTypeClasses
- Rank2Types
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds
- -fwrite-ide-info
- -hiedir=.hie

tests:
  {testname}:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O0
    - -fno-enable-rewrite-rules
    build-tools:
      tasty-discover:tasty-discover
    dependencies:
    - rulecheck
    - {packagename}
    - QuickCheck
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - ghc-prim
