name:                {testname}
version:             0.1.0

dependencies:
- base >= 4.12 && < 5

default-extensions:
- BangPatterns
- ConstraintKinds
- DeriveAnyClass
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- KindSignatures
- MagicHash # This is necessary for FastMath, for example
- MultiParamTypeClasses
- Rank2Types
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-binds
- -fno-warn-unused-matches
- -fno-warn-unused-imports
- -fwrite-ide-info
- -hiedir=.hie

tests:
  {testname}:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O0
    - -fno-enable-rewrite-rules
    build-tools:
      tasty-discover:tasty-discover
    dependencies:
    - rulecheck-runtime
    - {packagename}
    - QuickCheck
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - ghc-prim
                 # Extra deps for specific modules
                 # If this causes a problem, setup per-module package.yaml
    - containers # Required for algebraic-graphs
    - deepseq    # Required for basement
