name:                demo-test
version:             0.1.0

dependencies:
- base >= 4.12 && < 5

default-extensions:
- BangPatterns
- ConstraintKinds
- DeriveAnyClass
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- KindSignatures
- MultiParamTypeClasses
- Rank2Types
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds
- -fwrite-ide-info
- -hiedir=.hie

tests:
  demo-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O0
    - -fno-enable-rewrite-rules
    build-tools:
      tasty-discover:tasty-discover
    dependencies:
    - rulecheck
    - demo-domain
    - QuickCheck
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    # These are ALL the non-boot packages with rewrite rules in the resolver:
    # - adjunctions
    # - aeson
    # - Agda
    # - algebraic-graphs
    # - arithmoi
    # - base-compat
    # - basement
    # - bifunctors
    # - binary-list
    # - bits
    # - blaze-builder
    # - blaze-textual
    # - boring
    # - brick
    # - byteable
    # - bytestring-builder
    # - bytestring-strict-builder
    # - bytestring-trie
    # - carray
    # - case-insensitive
    # - cassava
    # - clash-lib
    # - clash-prelude
    # - Color
    # - concise
    # - conduit
    # - cryptohash
    # - csv-conduit
    # - cubicbezier
    # - doctest
    # - doctest-parallel
    # - equational-reasoning
    # - extensible-effects
    # - fast-builder
    # - fast-math
    # - fgl
    # - fin
    # - fixed-vector
    # - flat
    # - focus
    # - foundation
    # - fourmolu
    # - freer-simple
    # - ghc-exactprint
    # - ghc-lib
    # - ghc-lib-parser
    # - graph-wrapper
    # - half
    # - haskell-src-exts
    # - hasktags
    # - heap
    # - hgeometry
    # - hmatrix-vector-sized
    # - hourglass
    # - hw-streams
    # - ilist
    # - integer-roots
    # - interpolate
    # - kan-extensions
    # - lens
    # # Requires native dep?
    # # - leveldb-haskell
    # - linear
    # - ListLike
    # - log-domain
    # - logfloat
    # - massiv
    # - massiv-io
    # - matrix
    # - matrix-static
    # - memory
    # - MemoTrie
    # - microlens
    # - microlens-ghc
    # - microlens-platform
    # - mod
    # - mono-traversable
    # # Requires native dep?
    # # - mysql-simple
    # - natural-transformation
    # - nonempty-containers
    # - numeric-prelude
    # - optics-core
    # - optics-extra
    # - ormolu
    # - parallel
    # - pinch
    # - pipes
    # - pipes-bytestring
    # - polysemy
    # - pqueue
    # - primitive
    # - protolude
    # - ptr-poker
    # - range
    # - Rattus
    # - reducers
    # - repa
    # - replace-megaparsec
    # - scientific
    # - semirings
    # - servant
    # - sized
    # - slist
    # - sorted-list
    # - storablevector
    # - streaming
    # - streaming-bytestring
    # - streamly
    # - subcategories
    # - synthesizer-core
    # - text-ansi
    # - text-short
    # - TypeCompose
    # - type-of-html
    # - unification-fd
    # - uniplate
    # - universum
    # - unix-time
    # - unordered-containers
    # - vector
    # - vinyl
    # - vty
    # - wide-word
    # - zlib
