name:                rulecheck
version:             0.1.0

dependencies:
- base >= 4.12 && < 5
- ghc == 9.0.2
- exceptions
- little-rio
- little-logger
- text
- generic-lens
- unliftio-core
- mtl
- ghc-paths
- hie-bios
- template-haskell
- hslogger

default-extensions:
- BangPatterns
- ConstraintKinds
- DataKinds
- DeriveAnyClass
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- KindSignatures
- MultiParamTypeClasses
- MultiWayIf
- Rank2Types
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds
- -fwrite-ide-info
- -hiedir=.hie

library:
  source-dirs: src

# TODO resurrect when we're ready to process files
# executables:
#   rulecheck-exe:
#     main:                Main.hs
#     source-dirs:         exe
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - rulecheck

tests:
  rulecheck-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rulecheck
    - tasty
    - tasty-hunit
