name:                rulecheck-runtime
version:             0.1.0

dependencies:
- base >= 4.12 && < 5
- ghc == 9.0.2
- aeson
# - basement
- containers
- deepseq
- directory
- exceptions
- little-rio
- little-logger
- text
- generic-lens
- unliftio-core
- mtl
- MissingH
- ghc-paths
- hie-bios
- template-haskell
# These are for prototyping the test interface:
- QuickCheck
- tasty
- tasty-quickcheck

default-extensions:
- BangPatterns
- ConstraintKinds
- DataKinds
- DeriveAnyClass
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- KindSignatures
- MagicHash
- MultiParamTypeClasses
- MultiWayIf
- Rank2Types
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds
- -fwrite-ide-info
- -hiedir=.hie

library:
  source-dirs: src
